# just add the keywords in this file
[selection]
authors = [
    "majumdar",
    "schehr",
    "benichou",
    "grabsch",
    "metzler",
    "klinger",
    "bruyne",
    "besse",
    "metzler",
    "belitz",
    "doussal",
    "krapivsky",
]
titles = [
    "integrable",
    "brownian",
    "loop",
    "jump proce",
    "first pass",
    "absorbing",
]
